---
- name: Create Resource Group
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ region }}"
